### ISSUE TITLE
Not possible to be used with useAsyncData?

### ISSUE THREAD

**Issue by marssantoso** [wobsoriano/nuxt-proxy#8]
I use the exact same config as in the README, and attempted to fetch the API from `useAsyncData` using `$fetch` like so:

```ts
const { data } = useAsyncData('todos', () => $fetch(`${baseUrl}/api/todos`), { transform: ({ data }) => data })
```

But the page is just stuck at pending. Using it with `useFetch` seems to be working fine, though. It's particularly weird since the [Nuxt's doc](https://v3.nuxtjs.org/getting-started/data-fetching#usefetch) mentioned that `useFetch` is just a wrapper around `useAsyncData` and `$fetch`.

It also seems to be working fine when `$fetch` is used in CSR (i.e., `onMounted`).

**Comment by ThunderAl197** [comment]
same problem. i did some research and realized that this is the problem comes from nitro/h3 server or nuxt internal request handling. it somehow just stuck when i tried to proxy any request.
i tried http-proxy http-proxy-middleware @refactorjs/http-proxy @nuxtjs-alt/proxy nuxt-proxy and event pure realization.
all same: it stuck with `await $fetch('/api/qwe')` but works well with `await $fetch('/api/qwe', {server: false})` (because this request invokes in browser), also just `http://localhost:3000/api/qwe` works good.
so, again, its only problem around SSR internal url/request handling

**Comment by ThunderAl197** [comment]
its possibly somewhere around creating and using `h3App.nodeHandler` and creating theirs own server side `fetch` which uses `localCall` to mimic regular http request to h3 server
https://github.com/unjs/nitro/blob/main/src/runtime/app.ts#L60-L61

**Comment by wobsoriano** [comment]
`useAsyncData` works perfectly fine. Check the playground.
